DROP DATABASE IF EXISTS smarttBot;
CREATE DATABASE smarttBot;

USE smarttBot;
CREATE TABLE `Cotações`
(
id INT AUTO_INCREMENT PRIMARY KEY,
moeda VARCHAR(30) NOT NULL,
periodicidade VARCHAR(30) NOT NULL,
`open` FLOAT NOT NULL,
`close` FLOAT NOT NULL,
high FLOAT NOT NULL,
low FLOAT NOT NULL,
`time` VARCHAR(30) NOT NULL
);
